version: '3.6'
services:
  mysql:
    image: mysql:5.7.26
    expose: 
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
      #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      api_network:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    expose: 
      - "80"
    ports:
      - "8080:80"
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    links:
      - mysql:db
    environment:
      - PMA_PASSWORD=1234
    networks:
      api_network:

  ubuntu:
    image: 1and1internet/ubuntu-16-apache-php-7.1
    depends_on:
      - mysql
    expose: 
      - "8080"
    environment:
    - COMPOSE_CONVERT_WINDOWS_PATHS=1
    ports:
      - "80:8080"
    working_dir: /var/www
    volumes:
      - ./ubuntu/blog:/var/www
    networks:
      api_network:

networks:
  api_network:
